### ISSUE TITLE
Marquee Label shifts down a bit in second round (Only on ios 6)

### ISSUE THREAD

**Issue by gauravkarmakar** [cbpowell/MarqueeLabel#108]
Hi Mr. Powell,

I am using your awesome MarqueeLabel in my project. It works extremely fine except for one minor glitch.
In ios 6, on device, I saw that the label shifts down by an offset in the second round (I am using MLContinuous) and on reaching the starting point it jumps back up (I guess you are replacing by a new subLabel, so the visible UI jerk in this case).
I am using auto-layout for my project and need to support ios 6 to 8.
Any idea what could be the issue?

Thanks.

**Comment by cbpowell** [comment]
Glad you find it useful! I unfortunately don't have any way to test on iOS 6 anymore, so I can't double check. Are you using the latest version of MarqueeLabel? That sounds like an issue that was fixed awhile back. Does it not occur (on the same build) when on iOS 7/8?

**Comment by gauravkarmakar** [comment]
Tried the latest version (2.2.5, right?) but the problem persists.
And no, it doesn't occur in ios 7/8. Following is a cropped screenshot from ios 6 device (even I have it only on an iPod, hope that is not a plausible cause)
![screen shot 2015-07-08 at 3 58 16 pm](https://cloud.githubusercontent.com/assets/12974833/8568352/891e8366-258a-11e5-9f11-083b232ae5b4.png)

In the image you can see "busy" (the first word and of course the following words) has shifted down in the second round.

Thanks.

**Comment by cbpowell** [comment]
Well I wasn't ever able to think of a reason why this would happen on iOS 6, but the new [release v2.3.0](https://github.com/cbpowell/MarqueeLabel/releases/tag/2.3.0) should hopefully fix this. CAReplicatorLayer has been available since iOS 3.0, so there shouldn't be any compatibility issue.

Let me know if it fixes things!

**Comment by gauravkarmakar** [comment]
Sure.
That project of mine is on hold as of now but I would try it out as soon as I get a chance.
Thanks again Mr. Powell. :-)

**Comment by cbpowell** [comment]
Pretty sure this is fixed, so I'll go ahead and close the issue. Let me know if you still have a problem!
